### ISSUE TITLE
Window Base Class + Functionalities

### ISSUE THREAD

**Issue by JungDefiant** [chidmdxx/iThrive2018#4]
- Code abstract UI component for all window objects
- Windows only interact when it is the CurrentWindow (click on UI element to make CurrentWindow)
- Tabs: If we stick with an early 2000's OS, we might not need tabs
- Messenger: Select dialogue options, 'type out' responses (REF: Emily Is Away)

**Comment by chidmdxx** [comment]
do we need this?
sounds like a good design idea, but could be better to start coding and later on see what can we generalize, could be better to custom make all the windows for time sake

**Comment by JungDefiant** [comment]
Yes.

I feel like it's going to simplify all of our code having an abstract class
that we can inherit from. It won't get messy later.
